### ISSUE TITLE
can't build on Ubuntu Noble 24.04

### ISSUE THREAD

**Issue by ezbik** [Lochnair/xt_tls#64]
```
# make
make -C ipt
make[1]: Entering directory '/usr/src/xt_tls/ipt'
cc -I../src -fPIC   -c -o libxt_tls.o libxt_tls.c
cc -shared -o libxt_tls.so libxt_tls.o;
/usr/bin/ld: libxt_tls.o: in function `_init':
libxt_tls.c:(.text+0x35f): multiple definition of `_init'; /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/crti.o:(.init+0x0): first defined here
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:7: libxt_tls.so] Error 1
rm libxt_tls.o
make[1]: Leaving directory '/usr/src/xt_tls/ipt'
make: *** [Makefile:6: all] Error 2
```

* gcc-13
* kernel 6.8.0-11-generic

Thanks.

**Comment by Lochnair** [comment]
Thanks for the report, if you're still looking for a solution, I've pushed a fix to #65 that works on my 24.04 system. Please test if that works for you.

**Comment by ezbik** [comment]
Thank you, I confirm, it was built OK.

**Comment by jibanes** [comment]
Works here too.
