### ISSUE TITLE
Failed to compile in ubuntu 20.04

### ISSUE THREAD

**Issue by yiguihai** [Lochnair/xt_tls#51]
I'm having a little trouble compiling this project
```
runner@fv-az167-190:/tmp/xt_tls$ sudo make
make -C ipt
make[1]: Entering directory '/tmp/xt_tls/ipt'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/tmp/xt_tls/ipt'
make -C src
make[1]: Entering directory '/tmp/xt_tls/src'
make -C /lib/modules/5.8.0-1042-azure/build M=/tmp/xt_tls/src modules
make[2]: Entering directory '/usr/src/linux-headers-5.8.0-1042-azure'
  CC [M]  /tmp/xt_tls/src/xt_tls_main.o
  CC [M]  /tmp/xt_tls/src/hostset.o
/tmp/xt_tls/src/hostset.c: In function ‘hs_init’:
/tmp/xt_tls/src/hostset.c:52:6: error: passing argument 4 of ‘proc_create_data’ from incompatible pointer type [-Werror=incompatible-pointer-types]
   52 |      &proc_fops, hs);
      |      ^~~~~~~~~~
      |      |
      |      struct file_operations *
In file included from /tmp/xt_tls/src/hostset.c:9:
./include/linux/proc_fs.h:103:31: note: expected ‘const struct proc_ops *’ but argument is of type ‘struct file_operations *’
  103 | extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
      |                               ^~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:286: /tmp/xt_tls/src/hostset.o] Error 1
make[2]: *** [Makefile:1785: /tmp/xt_tls/src] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.8.0-1042-azure'
make[1]: *** [Makefile:10: default] Error 2
make[1]: Leaving directory '/tmp/xt_tls/src'
make: *** [Makefile:7: all] Error 2
```
ubuntu-20.04
